name: PA3

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: assignments/PA3
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install libfl-dev
      run: sudo apt-get install libfl-dev
    - name: Compile
      run: make && make parser
    - name: Run tests
      run: ./test.sh
